--- Editor chrome, native syntax, and core UI groups.

local util = require("themes.umbra.util")

---@param p table Resolved palette
---@param sem table Semantic derived colors
---@param cfg UmbraConfig
---@return table<string, vim.api.keyset.highlight>
return function(p, sem, cfg)
  local bg, fg, acc, git, diag = p.bg, p.fg, p.accent, p.git, p.diag
  local none = p.none
  local comment = { fg = fg.comment, italic = cfg.italic_comments or nil }
  local keyword = cfg.bold_keywords and { fg = acc.purple, bold = true } or { fg = acc.purple }
  local selected = { fg = fg.base, bg = bg.active, bold = true }

  local fallback = p.fallback_base or "#1A1E27"
  local cursor_bg = bg.base == none and fallback or bg.base

  return {
    Normal = { fg = fg.base, bg = bg.base },
    NormalNC = cfg.dim_inactive and { fg = fg.muted, bg = bg.base } or { fg = fg.base, bg = bg.base },
    NormalFloat = { fg = fg.base, bg = bg.float },
    FloatBorder = { fg = p.border, bg = bg.float },
    FloatTitle = { fg = acc.indigo, bg = bg.float, bold = true },
    FloatFooter = { fg = fg.muted, bg = bg.float },
    ColorColumn = { bg = bg.cursorline },
    Cursor = { fg = cursor_bg, bg = fg.base },
    lCursor = { fg = cursor_bg, bg = fg.base },
    CursorIM = { fg = cursor_bg, bg = fg.base },
    TermCursor = { fg = cursor_bg, bg = acc.indigo },
    CursorColumn = { bg = bg.cursorline },
    CursorLine = { bg = bg.cursorline },
    CursorLineNr = { fg = acc.indigo, bold = true },
    LineNr = { fg = fg.faint },
    LineNrAbove = { fg = fg.faint },
    LineNrBelow = { fg = fg.faint },
    SignColumn = { fg = fg.muted, bg = none },
    FoldColumn = { fg = fg.faint, bg = none },
    Folded = { fg = fg.dim, bg = bg.cursorline },
    WinSeparator = { fg = p.border, bg = none },
    VertSplit = { fg = p.border, bg = none },
    EndOfBuffer = { fg = bg.base },
    NonText = { fg = fg.faint },
    Whitespace = { fg = fg.faint },
    SpecialKey = { fg = fg.faint },
    Conceal = { fg = fg.muted },
    Directory = { fg = acc.blue },
    Title = { fg = acc.indigo, bold = true },
    MatchParen = { fg = acc.orange, bg = bg.match, bold = true },
    Visual = { bg = bg.selection },
    VisualNOS = { bg = bg.selection },
    Search = { fg = fg.base, bg = bg.search },
    IncSearch = { fg = bg.dark, bg = acc.orange, bold = true },
    CurSearch = { fg = bg.dark, bg = acc.orange, bold = true },
    Substitute = { fg = bg.dark, bg = acc.red },
    QuickFixLine = { bg = bg.active, bold = true },
    WildMenu = { fg = bg.dark, bg = acc.indigo },
    Winbar = { fg = fg.dim, bg = none },
    WinbarNC = { fg = fg.muted, bg = none },

    ErrorMsg = { fg = diag.error },
    WarningMsg = { fg = diag.warn },
    ModeMsg = { fg = fg.dim },
    MoreMsg = { fg = acc.cyan },
    Question = { fg = acc.blue },
    MsgArea = { fg = fg.dim },
    MsgSeparator = { fg = p.border },

    Pmenu = { fg = fg.dim, bg = bg.float },
    PmenuSel = selected,
    PmenuKind = { fg = acc.blue, bg = bg.float },
    PmenuKindSel = { fg = acc.blue, bg = bg.active },
    PmenuExtra = { fg = fg.muted, bg = bg.float },
    PmenuExtraSel = { fg = fg.dim, bg = bg.active },
    PmenuSbar = { bg = bg.float },
    PmenuThumb = { bg = p.border_bright },

    StatusLine = { fg = fg.dim, bg = bg.dark },
    StatusLineNC = { fg = fg.muted, bg = bg.dark },
    TabLine = { fg = fg.muted, bg = bg.dark },
    TabLineFill = { bg = bg.base },
    TabLineSel = { fg = fg.base, bg = bg.base },

    Comment = comment,
    Constant = { fg = acc.pink },
    String = { fg = acc.emerald },
    Character = { fg = acc.emerald },
    Number = { fg = acc.peach },
    Float = { fg = acc.peach },
    Boolean = { fg = acc.peach },
    Identifier = { fg = fg.base },
    Function = { fg = acc.blue },
    Statement = keyword,
    Conditional = keyword,
    Repeat = keyword,
    Label = keyword,
    Operator = { fg = acc.sky },
    Keyword = keyword,
    Exception = keyword,
    PreProc = { fg = acc.mauve },
    Include = { fg = acc.mauve },
    Define = { fg = acc.mauve },
    Macro = { fg = acc.mauve },
    PreCondit = { fg = acc.mauve },
    Type = { fg = acc.teal },
    StorageClass = { fg = acc.teal },
    Structure = { fg = acc.teal },
    Typedef = { fg = acc.teal },
    Special = { fg = acc.cyan },
    SpecialChar = { fg = acc.cyan },
    Tag = { fg = acc.red },
    Delimiter = { fg = fg.dim },
    SpecialComment = util.style(comment, { fg = acc.cyan }),
    Debug = { fg = acc.red },
    Underlined = { fg = acc.blue, underline = true },
    Ignore = { fg = fg.muted },
    Error = { fg = diag.error },
    Todo = { fg = bg.dark, bg = acc.orange, bold = true },

    DiffAdd = { bg = sem.diff.add },
    DiffChange = { bg = sem.diff.change },
    DiffDelete = { bg = sem.diff.delete },
    DiffText = { bg = sem.diff.text },
    diffAdded = { fg = git.add },
    diffRemoved = { fg = git.delete },
    diffChanged = { fg = git.change },
    diffFile = { fg = acc.blue },
    diffLine = { fg = fg.muted },
    Added = { fg = git.add },
    Removed = { fg = git.delete },
    Changed = { fg = git.change },

    GitSignsAdd = { fg = git.add },
    GitSignsChange = { fg = git.change },
    GitSignsDelete = { fg = git.delete },
    GitSignsChangedelete = { fg = git.change },
    GitSignsAddNr = { fg = git.add },
    GitSignsChangeNr = { fg = git.change },
    GitSignsDeleteNr = { fg = git.delete },
    GitSignsAddInline = { bg = sem.inline.add },
    GitSignsDeleteInline = { bg = sem.inline.delete },
    GitSignsChangeInline = { bg = sem.inline.change },
    GitSignsCurrentLineBlame = { fg = fg.faint, italic = true },
    GitSignsAddPreview = { fg = git.add },
    GitSignsDeletePreview = { fg = git.delete },
    GitSignsUntracked = { fg = git.untracked },
  }
end
