-- Single source of truth for glyphs. Requires a Nerd Font.

return {
  diagnostics = {
    Error = "",
    Warn = "",
    Info = "",
    Hint = "",
  },
  git = {
    added = "",
    modified = "",
    removed = "",
    branch = "",
    unstaged = "",
    staged = "",
    conflict = "",
    untracked = "",
    ignored = "",
    renamed = "",
  },
  kinds = {
    Text = "󰉿", Method = "󰊕", Function = "󰊕", Constructor = "", Field = "󰜢",
    Variable = "󰀫", Class = "󰠱", Interface = "", Module = "", Property = "󰜢",
    Unit = "󰑭", Value = "󰎠", Enum = "", Keyword = "󰌋", Snippet = "", Color = "󰏘",
    File = "󰈙", Reference = "󰈇", Folder = "󰉋", EnumMember = "", Constant = "󰏿",
    Struct = "󰙅", Event = "", Operator = "󰆕", TypeParameter = "", Copilot = "",
    Namespace = "󰅩", Package = "", String = "󰀬", Number = "󰎠", Boolean = "◩",
    Array = "󰅪", Object = "󰅩", Key = "󰌋", Null = "󰟢",
  },
  ui = {
    chevron_right = "›",
    arrow = "→",
    dot = "●",
    circle = "○",
    modified = "●",
    close = "󰅖",
    lock = "",
    bookmark = "",
    lightbulb = "󰌵",
    ellipsis = "…",
    prompt = "❯",
    fold_open = "",
    fold_closed = "",
    separator = "│",
    left_half = "",
    right_half = "",
    left_thin = "",
    right_thin = "",
  },
  ft = {
    default = "󰈙",
  },
}
